import { useState } from "react";
import { CircleDollarSign, Plus, Search } from "lucide-react";
import { adminCall } from "../api";
import type { PageResult, SaasUser } from "../types";
import { decimalToInteger, formatDate, formatMoney } from "../format";
import { useSaasLocale } from "../i18n";
import { ActionFeedback, Button, Card, Dialog, ErrorState, Field, Loading, Notice, Pagination, Status, Table, useAction, useResource } from "../components/ui";

export function UsersPanel({ showLedger }: { showLedger: (userId: string) => void }) {
  const { locale, text } = useSaasLocale();
  const [draft, setDraft] = useState({ query: "", status: "" });
  const [filters, setFilters] = useState(draft);
  const [page, setPage] = useState(1);
  const users = useResource(() => adminCall<PageResult<SaasUser>>("users.list", { query: filters.query, ...(filters.status ? { status: filters.status } : {}), page, pageSize: 20 }), [filters, page]);
  const [selected, setSelected] = useState<SaasUser | null>(null);
  const [creating, setCreating] = useState(false);
  const [crediting, setCrediting] = useState<SaasUser | null>(null);
  const [credit, setCredit] = useState({ amount: "", reason: "" });
  const [credentials, setCredentials] = useState({ email: "", password: "" });
  const [reason, setReason] = useState("");
  const action = useAction();
  return <Card title={text("用户管理", "Users")} action={<Button tone="primary" onClick={() => { setCredentials({ email: "", password: "" }); action.clear(); setCreating(true); }}><Plus size={16} />{text("创建账号", "Create account")}</Button>}><form className="saas-filters" onSubmit={event => { event.preventDefault(); setFilters(draft); setPage(1); users.reload(); }}><Field label={text("用户名 / 邮箱 / ID", "Username / email / ID")}><input maxLength={120} value={draft.query} onChange={event => setDraft({ ...draft, query: event.target.value })} /></Field><Field label={text("状态", "Status")}><select value={draft.status} onChange={event => setDraft({ ...draft, status: event.target.value })}><option value="">{text("全部", "All")}</option><option value="active">{text("正常", "Active")}</option><option value="banned">{text("封禁", "Banned")}</option></select></Field><Button type="submit" busy={users.loading}><Search size={16} />{text("查询", "Search")}</Button></form>
    {users.loading ? <Loading /> : users.error ? <ErrorState error={users.error} retry={users.reload} /> : users.data && <><Table items={users.data.items} rowKey={user => user.id} columns={[
      { label: text("用户", "User"), render: user => <><strong>{user.email || `@${user.login}`}</strong>{user.email && <small>@{user.login}</small>}<small className="saas-mono saas-muted">{user.id}</small></> },
      { label: text("余额 / 冻结", "Balance / reserved"), render: user => <>{formatMoney(user.balanceMicros, locale)}<small>{formatMoney(user.frozenMicros, locale)} {text("冻结", "reserved")}</small>{!!user.debtMicros && <small className="saas-error-text">{text("欠费", "Debt")} {formatMoney(user.debtMicros, locale)}</small>}</> },
      { label: text("加入时间", "Joined"), render: user => formatDate(user.createdAt, locale) },
      { label: text("状态", "Status"), render: user => <Status value={user.status} /> },
      { label: text("操作", "Actions"), render: user => <div className="saas-row saas-wrap"><Button onClick={() => { setCrediting(user); setCredit({ amount: "", reason: "" }); action.clear(); }}><CircleDollarSign size={15} />{text("充值", "Credit")}</Button><Button onClick={() => showLedger(user.id)}>{text("余额流水", "View ledger")}</Button><Button tone={user.status === "active" ? "danger" : "default"} onClick={() => { setSelected(user); setReason(""); action.clear(); }}>{user.status === "active" ? text("封禁", "Suspend") : text("恢复", "Restore")}</Button></div> },
    ]} /><Pagination page={page} total={users.data.total} onPage={setPage} /></>}
    {creating && <Dialog title={text("创建邮箱账号", "Create email account")} busy={action.busy} onClose={() => setCreating(false)}><form className="saas-form" onSubmit={event => { event.preventDefault(); void action.run(() => adminCall("users.create", credentials), () => { setCreating(false); users.reload(); }); }}><Field label={text("邮箱", "Email")}><input autoFocus type="email" required maxLength={254} autoComplete="off" value={credentials.email} onChange={event => setCredentials({ ...credentials, email: event.target.value })} /></Field><Field label={text("初始密码", "Initial password")} hint={text("至少 8 个字符；请通过安全渠道交给用户。", "At least 8 characters; share it through a secure channel.")}><input type="password" required minLength={8} maxLength={128} autoComplete="new-password" value={credentials.password} onChange={event => setCredentials({ ...credentials, password: event.target.value })} /></Field><ActionFeedback action={action} /><div className="saas-actions"><Button disabled={action.busy} onClick={() => setCreating(false)}>{text("取消", "Cancel")}</Button><Button type="submit" tone="primary" busy={action.busy}>{text("创建账号", "Create account")}</Button></div></form></Dialog>}
    {crediting && <Dialog title={text("后台充值", "Credit user balance")} busy={action.busy} onClose={() => setCrediting(null)}><form className="saas-form" onSubmit={event => { event.preventDefault(); void action.run(() => adminCall("users.credit", { userId: crediting.id, amountMicros: decimalToInteger(credit.amount), reason: credit.reason.trim() }), () => { setCrediting(null); users.reload(); }); }}><Field label={text("用户", "User")}><input readOnly value={crediting.email || ("@" + crediting.login)} /></Field><Field label={text("充值金额（USD）", "Credit amount (USD)")}><input autoFocus required inputMode="decimal" value={credit.amount} onChange={event => setCredit({ ...credit, amount: event.target.value })} /></Field><Field label={text("充值原因", "Credit reason")} hint={text("该说明会写入余额流水和管理员审计记录。", "This note is recorded in the wallet ledger and administrator audit log.")}><textarea required maxLength={1024} value={credit.reason} onChange={event => setCredit({ ...credit, reason: event.target.value })} /></Field><ActionFeedback action={action} /><div className="saas-actions"><Button disabled={action.busy} onClick={() => setCrediting(null)}>{text("取消", "Cancel")}</Button><Button type="submit" tone="primary" busy={action.busy} disabled={!credit.amount || !credit.reason.trim()}>{text("确认充值", "Confirm credit")}</Button></div></form></Dialog>}
    {selected && <Dialog title={selected.status === "active" ? text("封禁用户", "Suspend user") : text("恢复用户", "Restore user")} busy={action.busy} onClose={() => setSelected(null)}><p><strong>@{selected.login}</strong></p><Notice tone="warning">{selected.status === "active" ? text("用户会话将撤销，API 密钥的新请求将被拒绝。余额和历史保留。", "Sessions will be revoked and new API-key requests rejected. Balance and history are retained.") : text("恢复后用户需重新登录，其他密钥限制仍然有效。", "The user must sign in again. Other API-key restrictions still apply.")}</Notice><form className="saas-form" onSubmit={event => { event.preventDefault(); void action.run(() => adminCall("users.status", { id: selected.id, status: selected.status === "active" ? "banned" : "active", reason: reason.trim() }), () => { setSelected(null); users.reload(); }); }}><Field label={text("审计原因", "Audit reason")}><textarea required maxLength={1000} value={reason} onChange={event => setReason(event.target.value)} /></Field><ActionFeedback action={action} /><div className="saas-actions"><Button disabled={action.busy} onClick={() => setSelected(null)}>{text("取消", "Cancel")}</Button><Button type="submit" tone={selected.status === "active" ? "danger" : "primary"} busy={action.busy} disabled={!reason.trim()}>{text("确认变更", "Confirm change")}</Button></div></form></Dialog>}
  </Card>;
}
