use crate::config_writer::ConfigWriter;
use crate::error::AppError;
use crate::paths::AppPaths;
use directories::BaseDirs;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RouteConfigWriteOutcome {
    pub target_key: String,
    pub path: String,
    pub status: String,
}

pub struct RouteConfigService;

impl RouteConfigService {
    pub async fn write_configs(
        paths: &AppPaths,
        base_url: &str,
    ) -> Result<Vec<RouteConfigWriteOutcome>, AppError> {
        let base_url = base_url.trim().trim_end_matches('/');
        if base_url.is_empty() {
            return Err(AppError::Validation {
                code: "validation.route_proxy_base_url_required",
                message: "Route proxy base URL is required before writing configs".to_string(),
                details: None,
                recoverable: true,
            });
        }

        let home = BaseDirs::new()
            .map(|dirs| dirs.home_dir().to_path_buf())
            .ok_or_else(|| AppError::Filesystem {
                code: "filesystem.home_not_found",
                message: "Could not resolve the current user home directory".to_string(),
                details: None,
                recoverable: false,
            })?;

        // Keep a local backup root available for later snapshot wiring.
        let _ = paths;

        let targets = [
            (
                "codex",
                home.join(".codex").join("config.toml"),
                render_codex_config(base_url),
            ),
            (
                "claude",
                home.join(".claude").join("settings.json"),
                render_claude_config(base_url),
            ),
            (
                "gemini",
                home.join(".gemini").join("settings.json"),
                render_gemini_config(base_url),
            ),
        ];

        let mut outcomes = Vec::with_capacity(targets.len());
        for (target_key, path, content) in targets {
            let write = ConfigWriter::write_atomic(&path, &content).await?;
            outcomes.push(RouteConfigWriteOutcome {
                target_key: target_key.to_string(),
                path: write.path,
                status: write.status,
            });
        }

        Ok(outcomes)
    }
}

pub fn render_codex_config(base_url: &str) -> String {
    format!(
        r#"# Generated by AI Switch route proxy
model_provider = "ai-switch"

[model_providers.ai-switch]
name = "AI Switch Route Proxy"
base_url = "{base_url}"
wire_api = "chat"
"#
    )
}

pub fn render_claude_config(base_url: &str) -> String {
    serde_json::json!({
        "aiSwitch": {
            "routeProxy": {
                "enabled": true,
                "baseUrl": base_url,
                "platform": "claude"
            }
        },
        "env": {
            "ANTHROPIC_BASE_URL": base_url,
            "AI_SWITCH_ROUTE_PROXY": base_url
        }
    })
    .to_string()
}

pub fn render_gemini_config(base_url: &str) -> String {
    serde_json::json!({
        "aiSwitch": {
            "routeProxy": {
                "enabled": true,
                "baseUrl": base_url,
                "platform": "gemini"
            }
        },
        "env": {
            "GEMINI_API_BASE_URL": base_url,
            "GOOGLE_GEMINI_BASE_URL": base_url,
            "AI_SWITCH_ROUTE_PROXY": base_url
        }
    })
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_codex_config_points_model_provider_to_proxy() {
        let rendered = render_codex_config("http://127.0.0.1:43111");
        assert!(rendered.contains("model_provider = \"ai-switch\""));
        assert!(rendered.contains("base_url = \"http://127.0.0.1:43111\""));
    }

    #[test]
    fn render_claude_and_gemini_include_route_metadata() {
        let claude = render_claude_config("http://127.0.0.1:43111");
        let gemini = render_gemini_config("http://127.0.0.1:43111");
        assert!(claude.contains("ANTHROPIC_BASE_URL"));
        assert!(claude.contains("\"platform\":\"claude\""));
        assert!(gemini.contains("GEMINI_API_BASE_URL"));
        assert!(gemini.contains("\"platform\":\"gemini\""));
    }
}
