use crate::config_writer::ConfigWriter;
use crate::error::AppError;
use crate::paths::AppPaths;
use crate::services::route_pool_service::normalize_platform;
use directories::BaseDirs;
use serde::{Deserialize, Serialize};
use std::path::{Path, PathBuf};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct RouteConfigWriteOutcome {
    pub target_key: String,
    pub path: String,
    pub status: String,
    pub route_proxy_key: String,
}

type TargetRender = fn(&str, &str) -> String;

struct RouteConfigTarget {
    key: &'static str,
    path: PathBuf,
    render: TargetRender,
}

pub struct RouteConfigService;

impl RouteConfigService {
    pub async fn write_configs(
        paths: &AppPaths,
        base_url: &str,
        platform: &str,
    ) -> Result<Vec<RouteConfigWriteOutcome>, AppError> {
        let base_url = base_url.trim().trim_end_matches('/');
        if base_url.is_empty() {
            return Err(AppError::Validation {
                code: "validation.route_proxy_base_url_required",
                message: "Route proxy base URL is required before writing configs".to_string(),
                details: None,
                recoverable: true,
            });
        }

        let home = BaseDirs::new()
            .map(|dirs| dirs.home_dir().to_path_buf())
            .ok_or_else(|| AppError::Filesystem {
                code: "filesystem.home_not_found",
                message: "Could not resolve the current user home directory".to_string(),
                details: None,
                recoverable: false,
            })?;

        // Keep a local backup root available for later snapshot wiring.
        let _ = paths;

        let target_key = normalize_platform(platform)?;
        let target = route_config_target(&home, &target_key)?;
        let route_proxy_key = generate_route_proxy_key();
        let content = (target.render)(base_url, &route_proxy_key);
        let write = ConfigWriter::write_atomic(&target.path, &content).await?;

        Ok(vec![RouteConfigWriteOutcome {
            target_key: target.key.to_string(),
            path: write.path,
            status: write.status,
            route_proxy_key,
        }])
    }
}

fn route_config_target(home: &Path, target_key: &str) -> Result<RouteConfigTarget, AppError> {
    match target_key {
        "codex" => Ok(RouteConfigTarget {
            key: "codex",
            path: home.join(".codex").join("config.toml"),
            render: render_codex_config,
        }),
        "claude" => Ok(RouteConfigTarget {
            key: "claude",
            path: home.join(".claude").join("settings.json"),
            render: render_claude_config,
        }),
        "gemini" => Ok(RouteConfigTarget {
            key: "gemini",
            path: home.join(".gemini").join("settings.json"),
            render: render_gemini_config,
        }),
        other => Err(AppError::Validation {
            code: "validation.route_config_target_unsupported",
            message: "Route config writing is not supported for this target".to_string(),
            details: Some(other.to_string()),
            recoverable: true,
        }),
    }
}

pub fn generate_route_proxy_key() -> String {
    format!("sk-ai-switch-{}", Uuid::new_v4().simple())
}

pub fn render_codex_config(base_url: &str, route_proxy_key: &str) -> String {
    format!(
        r#"# Generated by AI Switch route proxy
model_provider = "ai-switch"

[model_providers.ai-switch]
name = "AI Switch Route Proxy"
base_url = "{base_url}"
wire_api = "responses"
api_key = "{route_proxy_key}"
"#
    )
}

pub fn render_claude_config(base_url: &str, route_proxy_key: &str) -> String {
    serde_json::json!({
        "aiSwitch": {
            "routeProxy": {
                "enabled": true,
                "baseUrl": base_url,
                "platform": "claude",
                "apiKey": route_proxy_key
            }
        },
        "env": {
            "ANTHROPIC_BASE_URL": base_url,
            "AI_SWITCH_ROUTE_PROXY": base_url,
            "AI_SWITCH_ROUTE_PROXY_API_KEY": route_proxy_key
        }
    })
    .to_string()
}

pub fn render_gemini_config(base_url: &str, route_proxy_key: &str) -> String {
    serde_json::json!({
        "aiSwitch": {
            "routeProxy": {
                "enabled": true,
                "baseUrl": base_url,
                "platform": "gemini",
                "apiKey": route_proxy_key
            }
        },
        "env": {
            "GEMINI_API_BASE_URL": base_url,
            "GOOGLE_GEMINI_BASE_URL": base_url,
            "AI_SWITCH_ROUTE_PROXY": base_url,
            "AI_SWITCH_ROUTE_PROXY_API_KEY": route_proxy_key
        }
    })
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_codex_config_points_model_provider_to_proxy() {
        let rendered = render_codex_config("http://127.0.0.1:43111", "sk-ai-switch-test");
        assert!(rendered.contains("model_provider = \"ai-switch\""));
        assert!(rendered.contains("base_url = \"http://127.0.0.1:43111\""));
    }

    #[test]
    fn render_claude_and_gemini_include_route_metadata() {
        let claude = render_claude_config("http://127.0.0.1:43111", "sk-ai-switch-test");
        let gemini = render_gemini_config("http://127.0.0.1:43111", "sk-ai-switch-test");
        assert!(claude.contains("ANTHROPIC_BASE_URL"));
        assert!(claude.contains("\"platform\":\"claude\""));
        assert!(gemini.contains("GEMINI_API_BASE_URL"));
        assert!(gemini.contains("\"platform\":\"gemini\""));
    }

    #[test]
    fn generated_route_proxy_key_uses_sk_shape() {
        let key = generate_route_proxy_key();
        assert!(key.starts_with("sk-ai-switch-"));
        assert!(key.len() > "sk-ai-switch-".len() + 20);
    }

    #[test]
    fn render_codex_config_uses_responses_and_route_proxy_key() {
        let rendered = render_codex_config("http://127.0.0.1:43111", "sk-ai-switch-test");
        assert!(rendered.contains("model_provider = \"ai-switch\""));
        assert!(rendered.contains("base_url = \"http://127.0.0.1:43111\""));
        assert!(rendered.contains("wire_api = \"responses\""));
        assert!(rendered.contains("api_key = \"sk-ai-switch-test\""));
        assert!(!rendered.contains("wire_api = \"chat\""));
    }

    #[test]
    fn render_claude_and_gemini_include_route_proxy_key_metadata() {
        let claude = render_claude_config("http://127.0.0.1:43111", "sk-ai-switch-test");
        let gemini = render_gemini_config("http://127.0.0.1:43111", "sk-ai-switch-test");
        assert!(claude.contains("\"apiKey\":\"sk-ai-switch-test\""));
        assert!(claude.contains("AI_SWITCH_ROUTE_PROXY_API_KEY"));
        assert!(gemini.contains("\"apiKey\":\"sk-ai-switch-test\""));
        assert!(gemini.contains("AI_SWITCH_ROUTE_PROXY_API_KEY"));
    }

    #[tokio::test]
    async fn write_configs_rejects_unsupported_platform_without_writing_all_targets() {
        let temp = tempfile::tempdir().expect("temp dir");
        let paths = AppPaths::from_data_dir(temp.path().to_path_buf());
        let error = RouteConfigService::write_configs(&paths, "http://127.0.0.1:43111", "opencode")
            .await
            .expect_err("unsupported target");

        match error {
            AppError::Validation { code, details, .. } => {
                assert_eq!(code, "validation.route_config_target_unsupported");
                assert_eq!(details.as_deref(), Some("opencode"));
            }
            other => panic!("expected validation error, got {other:?}"),
        }
    }
}
